spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb?createDatabaseIfNotExist=true
    username: apallo
    password: zus2017
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



